site_name: OpenKuka
site_dir: '../openkuka.github.io'
site_description: 'Community documentation for the Kuka Robot Language'
site_author: Lionel du Peloux

google_analytics:
  - 'UA-136856150-1'
  - 'auto'
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  feature:
    tabs: true
  language: 'en'
plugins:
  - search
  - macros

repo_name: 'OpenKuka/Website'
repo_url: 'https://github.com/OpenKuka/Website'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/openkuka'
  
nav:
  - OpenKuka:
    - Home: index.md
    - Contributing: contributing.md
    - Author's notes: authors.md
  - Language Reference:
    - System.Types: krl/reference/system.types.md
    - System.Variables: krl/reference/system.variables.md
    - System.Functions: krl/reference/system.functions.md
    - System.Messages: krl/reference/system.messages.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.extrarawhtml
  - toc:
      permalink: true

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  # - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  # - 'https://unpkg.com/popper.js@1/dist/umd/popper.min.js'
  # - 'https://unpkg.com/tippy.js@4'
  # - 'javascripts/extra.js'

